# Generated by Django 3.2.12 on 2022-08-16 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('ID_BANCO', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOMBRE', models.CharField(default='', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['NOMBRE'],
            },
        ),
        migrations.CreateModel(
            name='EstadosDep',
            fields=[
                ('ID_ESTADO_DEP', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOMBRE', models.CharField(default='', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['NOMBRE'],
            },
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('ID_DEPOSITO', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CUENTA', models.BigIntegerField(default=0)),
                ('CVE_FOLIO', models.CharField(default='', max_length=240)),
                ('FECHA_DEPOSITO', models.DateField(blank=True, null=True)),
                ('FECHA_EN_BANCO', models.DateField(blank=True, null=True)),
                ('TIPO_CAMBIO', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('IMPORTE', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('EN_FIRME', models.BooleanField(default=False)),
                ('ID_AFILIADO', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fac.afiliado')),
                ('ID_BANCO', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oper.bancos')),
                ('ID_ESTADO_DEP', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oper.estadosdep')),
                ('ID_MONEDA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.monedas')),
                ('ID_RECEPTOR', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.ereceptora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-FECHA_DEPOSITO'],
            },
        ),
        migrations.AddConstraint(
            model_name='depositos',
            constraint=models.UniqueConstraint(fields=('ID_BANCO', 'CUENTA', 'CVE_FOLIO'), name='unique_dep'),
        ),
    ]
