# Generated by Django 3.2.12 on 2022-10-24 19:18

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0003_efectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectivo',
            name='IMPORTE_DISP',
            field=computed_property.fields.ComputedTextField(compute_from='_importe_disp', editable=False),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='SALDO',
            field=computed_property.fields.ComputedTextField(compute_from='_saldo', editable=False),
        ),
    ]
