# Generated by Django 3.2.12 on 2022-05-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_auto_20220507_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='ID_FILIADO',
            new_name='ID_AFILIADO',
        ),
    ]
