# Generated by Django 3.2.12 on 2022-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_auto_20220819_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdoc',
            name='NOMBRE',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
