# Generated by Django 3.2.12 on 2022-05-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_rename_id_filiado_afiliado_id_afiliado'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='facturas',
            index_together={('ID_EMISOR', 'SERIE', 'FOLIO', 'TIPO_DOCUMENTO')},
        ),
    ]
