# Generated by Django 3.2.12 on 2022-08-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_alter_tiposdoc_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='ID_TIPO_DOC',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to='fac.tiposdoc'),
        ),
    ]
