# Generated by Django 3.2.12 on 2022-09-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_alter_facturas_id_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosfac',
            name='NOMBRE',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
