# Generated by Django 3.2.12 on 2022-05-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_auto_20220509_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturas',
            options={},
        ),
    ]
