# Generated by Django 3.2.12 on 2022-09-26 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0005_alter_estadosfac_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='FECHA_REGISTRO',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturas',
            name='usuario',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EdosFacRet',
            fields=[
                ('ID_ESTADO_RET', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOMBRE', models.CharField(max_length=30, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['NOMBRE'],
            },
        ),
        migrations.AddField(
            model_name='facturas',
            name='ID_ESTADO_RET',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fac.edosfacret'),
        ),
    ]
