# Generated by Django 3.2.12 on 2022-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_alter_facturas_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='FECHA_EMISION',
            field=models.DateField(blank=True, null=True),
        ),
    ]
