# Generated by Django 3.2.12 on 2022-05-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0009_alter_facturas_fecha_emision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facturas',
        ),
    ]
