# Generated by Django 3.2.12 on 2022-10-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_auto_20220926_0415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oper', '0003_efectivo'),
        ('teso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartos',
            name='ID_FACTURA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reparto_factura', to='fac.facturas'),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('ID_CAJA', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('FECHA_DEPOSITO', models.DateField(blank=True, null=True)),
                ('IMPORTE', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('IMPORTE_DISP', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('ID_DEPOSITO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='oper.depositos')),
                ('ID_EFECTIVO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='oper.efectivo')),
                ('ID_MONEDA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.monedas')),
                ('usuario', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-FECHA_DEPOSITO'],
            },
        ),
    ]
