# Generated by Django 3.2.12 on 2022-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teso', '0002_auto_20221023_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='ID_DEPOSITO',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='ID_EFECTIVO',
        ),
        migrations.AddField(
            model_name='caja',
            name='FOLIO',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caja',
            name='SERIE',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='FECHA_DEPOSITO',
            field=models.DateField(auto_now_add=True),
        ),
    ]
